### ISSUE TITLE
Global Lua variables problem with new Redis

### ISSUE THREAD

**Issue by jarpineh** [lsbardel/python-stdnet#46] opened 2012-05-06 23:06 UTC
Hi.

I was trying to use the latest Stdnet version (0.7.c2). I have problems with all my Redis versions:
2.2 from Ubuntu 11.10
2.6.0-rc3 from redis.io
and a newer build from Redis repository

2.2 fails with pipeline command error and tests fail with "unknown SCRIPT command". I assume Stdnet 0.7+ requires Lua support in Redis. With 0.6 I have had no problems, but I'd like to use the new features...

Alas, the newer Redis fails with "Script attempted to create global variable" where variable depends upon the script used.

It seems Redis did allow global variables at some point:
https://github.com/antirez/redis/issues/484

So my question is which Redis version is supported at the moment?

Thank you.

**Comment by lsbardel** [comment] 2012-05-07 09:20
Hi,
I have seen the problem and I'm fixing it. I will release rc3 later on today.
Luca

**Comment by lsbardel** [comment] 2012-05-07 10:59
Stdnet 0.7 is for redis 2.6 only.
But I didn't test it with the latest redis release candidates.
The Issue is with redis explicitly raising an error when a script access a global variable.

**Comment by lsbardel** [comment] 2012-05-08 12:13
Fixed on 0.7 and master. I will release 0.7c3 to PyPi shortly.

**Closed as completed by lsbardel** 2012-05-08 12:13 UTC
Labels: bug, lua

**Comment by jarpineh** [comment] 2012-05-08 19:03
Thank you. I can confirm that my code works with Redis 2.6-rc3.

It was quite trivial to change code from 0.6.x to 0.7. Queries also seem much faster than before (with the same Redis).
